### ISSUE TITLE
建议加一个可以直接群内引用别人发的图片颜值打分

### ISSUE THREAD

**Issue by 360add** [KomoriDev/nonebot-plugin-beauty-rater#5]
![image](https://github.com/user-attachments/assets/ae27546a-37a5-4e73-9439-5c52aa41c5ac)

**Comment by 360add** [comment]
还有@用户头像给头像打分

**Comment by 360add** [comment]
目前在q群里回复别人的图片不会触发

**Comment by 360add** [comment]
发现了，要把前面的@人名删了就会打分了

**Comment by 360add** [comment]
颜值评分太低了，挺好看的脸只有60分
![image](https://github.com/user-attachments/assets/40805787-4f24-4925-bea3-5c21eaa6907e)

**Comment by KomoriDev** [comment]
1. 目前支持回复图片进行打分 (https://github.com/KomoriDev/nonebot-plugin-beauty-rater/commit/3bd52eaa0b399541ccaff411d6adb77847d91583)
2. 颜值评分数据来源与百度云
3. 不是所有用户头像都是真人头像，本插件暂不支持除人脸以外的图片进行打分。若支持 `@user` 进行打分，恐造成不必要的打扰
